#!/usr/bin/env bash
# displays information about subdomains

get_subdomain_info() {
    local domain="$1"
    local subdomain="$2"
    local subdomains=("www" "lb-01" "web-01" "web-02")

    if [ -n "$subdomain" ]; then
        subdomains=("$subdomain")
    fi

    for sub in "${subdomains[@]}"; do
        record_type=$(dig +short "$sub.$domain" | awk 'NR==1{print $4}')
        destination=$(dig +short "$sub.$domain" | awk 'NR==1{print $5}')
        echo "The subdomain $sub is a $record_type record and points to $destination"
    done
}

get_subdomain_info "$1" "$2"

