#!/usr/bin/env bash
# wrap scp to transfer files to a server

if (( $# < 3 )); then
	echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
	exit 1
fi

declare -a opts
opts+=('-o' 'StrictHostKeyChecking=no')
if [[ -n "$4" ]]; then
	opts+=('-i' "$4")
fi
scp "${opts[@]}" "$1" "${3}@${2}:~/"
