#!/usr/bin/env bash
# configure a server with Nginx, a redirect, and a custom 404 page

declare name

apt-get update
apt-get --yes install 'nginx'
name="$(uname --nodename)"

# Configure web-01
cat > '/etc/nginx/sites-available/web-01' << EOF
server {
	listen 80 default_server;
	listen [::]:80 default_server ipv6only=on;
	root /var/www/html;
	index index.html;

	add_header X-Served-By web-01;

	error_page 404 /404.html;

	location /404.html {
		internal;
	}
	location /redirect_me {
		return 301 http://example.com/;
	}
}
EOF

# Configure web-02
cat > '/etc/nginx/sites-available/web-02' << EOF
server {
	listen 80 default_server;
	listen [::]:80 default_server ipv6only=on;
	root /var/www/html;
	index index.html;

	add_header X-Served-By web-02;

	error_page 404 /404.html;

	location /404.html {
		internal;
	}
	location /redirect_me {
		return 301 http://example.com/;
	}
}
EOF

ln -sf '/etc/nginx/sites-available/web-01' '/etc/nginx/sites-enabled/web-01'
ln -sf '/etc/nginx/sites-available/web-02' '/etc/nginx/sites-enabled/web-02'

mkdir --parents '/var/www/html'
echo 'Hello World!' > '/var/www/html/index.html'
echo 'Ceci n'\''est pas une page' > '/var/www/html/404.html'
service nginx reload
service nginx restart

