#!/bin/bash
# configure a server with Nginx, a redirect, and a custom 404 page

apt-get update
apt-get --yes install 'haproxy'

# Configure HAProxy
cat > '/etc/haproxy/haproxy.cfg' << EOF
global
  log /dev/log local0
  log /dev/log local1 notice
  chroot /var/lib/haproxy
  stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
  stats timeout 30s
  user haproxy
  group haproxy
  daemon

defaults
  log global
  mode http
  option httplog
  option dontlognull
  timeout connect 5000
  timeout client 50000
  timeout server 50000

frontend olubunday.tech
  bind *:80
  default_backend web_servers

backend http_back
  balance roundrobin
  server web-01 18.235.255.31:80 check
  server web-02 52.206.199.245:80 check
EOF

# Configure hostname
echo "[STUDENT_ID]-web-01" > /etc/hostname
hostnamectl set-hostname [STUDENT_ID]-web-01

service haproxy reload
service haproxy restart
