#!/usr/bin/env bash
# configure a server with Nginx, a redirect, and a custom 404 page

apt-get update
apt-get --yes install 'haproxy'
cat > '/etc/haproxy/haproxy.cfg' << EOF
global
	maxconn 2000
	user haproxy
	group haproxy

defaults
	mode http
	retries 5
	timeout connect 5s
	timeout client 60s
	timeout server 60s

frontend third-serenade.tech
	bind *:80
	default_backend web_servers

backend web_servers
	balance roundrobin
	server web-01 18.235.255.31:80
	server web-02 52.206.199.245:80
EOF
update-rc.d haproxy defaults
service haproxy reload
service haproxy restart
